### ISSUE TITLE
Unicode error when asking for PIN

### ISSUE THREAD

**Issue by techge** [vletoux/OpenPGP-CSP#2] opened 2018-01-08 16:01 UTC
Hi,

I like to track a little issue here:

Windows asking for user/admin PIN has unicode error (see screenshots attached)

![screenshot_2](https://user-images.githubusercontent.com/25867995/34679162-5f9bdc64-f495-11e7-8df6-034fb2b29cba.png)

![screenshot_3](https://user-images.githubusercontent.com/25867995/34679154-5aa4f8c6-f495-11e7-8a39-e09ead988681.png)

**Comment by vletoux** [comment] 2018-01-08 18:08
Except that the Windows does not include any placeholder here:
![image](https://user-images.githubusercontent.com/10632326/34684954-193ea582-f4a7-11e7-93f8-04aed5848058.png)
![image](https://user-images.githubusercontent.com/10632326/34685006-3c4e8146-f4a7-11e7-9b4d-b6897bba8a33.png)

I do not understand how such character can be shown here.

**Comment by techge** [comment] 2018-01-08 18:11
Hi Vincent,
mh, that's strange indeed. Is it may connected to Windows version? I used Win2k8 in English...

**Comment by vletoux** [comment] 2018-06-07 17:18
Can't reproduce. Can you still reproduce it?
If not, I'll close the issue.

**Comment by alex-nitrokey** [comment] 2018-06-11 07:11
The issue is still valid. I'll try on Win Server 2016 as soon I have time for it.
May, but probably not related: the mentioned test machine with Win2008 R2 runs on Virtualbox.

PS: On Win10 I never got this afair

**Comment by vletoux** [comment] 2018-06-11 07:55
a "certutil -scinfo" is enough to trigger the PIN dialog prompt if a certificate is present on the card.
The dialogs are written by the Windows dialog editor and this is the first time in more than 10 years of programming that I see this.
Would the presence of a third party program (used to "secure the PIN entry") explain this case ?

**Comment by vletoux** [comment] 2018-06-11 07:56
Or are you sending the "pin prompt" text in ANSI instead of UNICODE ?

**Comment by alex-nitrokey** [comment] 2018-06-25 14:49
I am sorry for the delay.

The system is a clean installation of win 2k8, so no special third party program. The funny signs are appearing without me interacting and are there every time the PIN prompt appears. It is really strange that the odd signs are different for user and admin pin, too.

I don't know how I could send ANSI text to the prompt anyway.

At least, I indeed only saw it on this win2k8 installation yet. So this shouldn't be much important. I still try to find the time to test it on win2016...

**Comment by vletoux** [comment] 2018-07-03 19:56
Can you pack to me a VM to be able to test it ?
My guest is that you have a 3rd party program.

**Comment by vletoux** [comment] 2018-07-18 15:41
Fixed by 79ebdedaf65a126a9b64323d116f2a2692bd9b1d
![image](https://user-images.githubusercontent.com/10632326/42892258-aeae1954-8ab1-11e8-92c1-b7588aea4981.png)

**Closed as completed by vletoux** 2018-07-18 15:41 UTC
Labels: invalid
